version: "3"
services:
  database:
    image: postgres:13.2
    container_name: "appdb"
    volumes:
      - database:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    ports:
        - 5432:5432

volumes:
    database:
      driver: local
